Imports Datos
Imports Entidades
Public Class N_IRIS_WEBF_CMVM_BUSCA_LISTA_DEST_COPY
    Dim DD_Data As D_IRIS_WEBF_CMVM_BUSCA_LISTA_DEST_COPY
    Sub New()
        DD_Data = New D_IRIS_WEBF_CMVM_BUSCA_LISTA_DEST_COPY
    End Sub
    Function IRIS_WEBF_CMVM_BUSCA_LISTA_DEST() As List(Of E_IRIS_WEBF_CMVM_BUSCA_LISTA_DEST)
        Return DD_Data.IRIS_WEBF_CMVM_BUSCA_LISTA_DEST()
    End Function
    Function IRIS_WEBF_CMVM_BUSCA_LISTA_COPY() As List(Of E_IRIS_WEBF_CMVM_BUSCA_LISTA_COPY)
        Return DD_Data.IRIS_WEBF_CMVM_BUSCA_LISTA_COPY()
    End Function
End Class
