Imports Entidades
Imports Datos
Public Class N_IRIS_WEBF_CMVM_BUSCA_LISTA_TICKET
    Dim DD_Data As D_IRIS_WEBF_CMVM_BUSCA_LISTA_TICKET
    Sub New()
        DD_Data = New D_IRIS_WEBF_CMVM_BUSCA_LISTA_TICKET
    End Sub
    Function IRIS_WEBF_CMVM_BUSCA_LISTA_TICKET(ByVal ID_USUARIO As Long) As List(Of E_IRIS_WEBF_CMVM_BUSCA_LISTA_TICKET)
        Return DD_Data.IRIS_WEBF_CMVM_BUSCA_LISTA_TICKET(ID_USUARIO)
    End Function
End Class
