'Importar Capas
Imports Datos
Imports Entidades
Public Class N_IRIS_WEBF_HOST_BUSCA_DATOS_PACIENTE_Y_EXAMENES_POR_FOLIO_AVIS_2
    'Declaraciones Generales
    Dim DD_Data As D_IRIS_WEBF_HOST_BUSCA_DATOS_PACIENTE_Y_EXAMENES_POR_FOLIO_AVIS_2
    Sub New()
        DD_Data = New D_IRIS_WEBF_HOST_BUSCA_DATOS_PACIENTE_Y_EXAMENES_POR_FOLIO_AVIS_2
    End Sub
    Function IRIS_WEBF_HOST_BUSCA_DATOS_PACIENTE_Y_EXAMENES_POR_FOLIO_AVIS_2(ByVal FOLIO As String) As List(Of E_IRIS_WEBF_HOST_BUSCA_DATOS_PACIENTE_Y_EXAMENES_POR_FOLIO_AVIS_2)
        Return DD_Data.IRIS_WEBF_HOST_BUSCA_DATOS_PACIENTE_Y_EXAMENES_POR_FOLIO_AVIS_2(FOLIO)
    End Function
    Function IRIS_WEBF_HOST_BUSCA_PACIENTES_SIN_RUT_AVIS() As List(Of E_IRIS_WEBF_HOST_BUSCA_DATOS_PACIENTE_Y_EXAMENES_POR_FOLIO_AVIS_2)
        Return DD_Data.IRIS_WEBF_HOST_BUSCA_PACIENTES_SIN_RUT_AVIS()
    End Function
    Function IRIS_WEBF_HOST_BUSCA_DATOS_PACIENTE_Y_EXAMENES_POR_FOLIO_SIDRA_2_GLOBAL(ByVal FOLIO As String) As List(Of E_IRIS_WEBF_HOST_BUSCA_DATOS_PACIENTE_Y_EXAMENES_POR_FOLIO_AVIS_2)
        Return DD_Data.IRIS_WEBF_HOST_BUSCA_DATOS_PACIENTE_Y_EXAMENES_POR_FOLIO_SIDRA_2_GLOBAL(FOLIO)
    End Function



    Function IRIS_WEBF_HOST_BUCA_DATOS_PACIENTE_POR_RUT_AVIS(ByVal RUT As String) As List(Of E_IRIS_WEBF_HOST_BUSCA_DATOS_PACIENTE_Y_EXAMENES_POR_FOLIO_AVIS_2)
        Return DD_Data.IRIS_WEBF_HOST_BUCA_DATOS_PACIENTE_POR_RUT_AVIS(RUT)
    End Function
End Class