'Importar Capas
Imports Datos
Imports Entidades
Public Class N_IRIS_WEBF_GRABA_ATENCION_PROGRA2_PRO_SECTOR_AVIS
    'Declaraciones Generales
    Dim DD_Data As D_IRIS_WEBF_GRABA_ATENCION_PROGRA2_PRO_SECTOR_AVIS
    Sub New()
        DD_Data = New D_IRIS_WEBF_GRABA_ATENCION_PROGRA2_PRO_SECTOR_AVIS
    End Sub
    Function IRIS_WEBF_GRABA_ATENCION_PROGRA2_PRO_SECTOR_AVIS(ByVal ATE_NUM As String,
                                                              ByVal ID_PACIENTE As Integer,
                                                              ByVal ID_USUARIO As Integer,
                                                              ByVal ATE_FUR As String,
                                                              ByVal ID_PROCE As Integer,
                                                              ByVal ID_ORDEN As Integer,
                                                              ByVal ID_TP_PACI As Integer,
                                                              ByVal ID_DOCTOR As Integer,
                                                              ByVal ID_PREVE As Integer,
                                                              ByVal ID_LOCAL As Integer,
                                                              ByVal ID_ESTADO As Integer,
                                                              ByVal ATE_OBS As String,
                                                              ByVal ATE_CAMA As String,
                                                              ByVal ATE_AÑO As Integer,
                                                              ByVal ATE_MES As Integer,
                                                              ByVal ATE_DIA As Integer,
                                                              ByVal ATE_TOTAL As Integer,
                                                              ByVal ATE_TOTAL_PREVI As Integer,
                                                              ByVal ATE_TOTAL_COPA As Integer,
                                                              ByVal ID_PROGRA As Integer,
                                                              ByVal ATE_RETIRO As String,
                                                              ByVal SECTOR As Integer,
                                                              ByVal ATE_AVIS As String,
                                                              ByVal Interno As String,
                                                              ByVal Diag As String,
                                                              ByVal Diag2 As String,
                                                              ByVal VIH As String,
                                                              ByVal dni As String,
                                                              ByVal ATE_TM As String,
                                                              ByVal SUB_PROGRAMA As String) As Integer
        Return DD_Data.IRIS_WEBF_GRABA_ATENCION_PROGRA2_PRO_SECTOR_AVIS(ATE_NUM,
                                                                        ID_PACIENTE,
                                                                        ID_USUARIO,
                                                                        ATE_FUR,
                                                                        ID_PROCE,
                                                                        ID_ORDEN,
                                                                        ID_TP_PACI,
                                                                        ID_DOCTOR,
                                                                        ID_PREVE,
                                                                        ID_LOCAL,
                                                                        ID_ESTADO,
                                                                        ATE_OBS,
                                                                        ATE_CAMA,
                                                                        ATE_AÑO,
                                                                        ATE_MES,
                                                                        ATE_DIA,
                                                                        ATE_TOTAL,
                                                                        ATE_TOTAL_PREVI,
                                                                        ATE_TOTAL_COPA,
                                                                        ID_PROGRA,
                                                                        ATE_RETIRO,
                                                                        SECTOR,
                                                                        ATE_AVIS,
                                                                        Interno,
                                                                         Diag, Diag2,
                                                                        VIH,
                                                                        dni,
                                                                        ATE_TM, SUB_PROGRAMA)
    End Function
    Function IRIS_WEBF_GRABA_ATENCION_PROGRA2_PRO_SECTOR_OMI(ByVal ATE_NUM As String,
                                                              ByVal ID_PACIENTE As Integer,
                                                              ByVal ID_USUARIO As Integer,
                                                              ByVal ATE_FUR As String,
                                                              ByVal ID_PROCE As Integer,
                                                              ByVal ID_ORDEN As Integer,
                                                              ByVal ID_TP_PACI As Integer,
                                                              ByVal ID_DOCTOR As Integer,
                                                              ByVal ID_PREVE As Integer,
                                                              ByVal ID_LOCAL As Integer,
                                                              ByVal ID_ESTADO As Integer,
                                                              ByVal ATE_OBS As String,
                                                              ByVal ATE_CAMA As String,
                                                              ByVal ATE_AÑO As Integer,
                                                              ByVal ATE_MES As Integer,
                                                              ByVal ATE_DIA As Integer,
                                                              ByVal ATE_TOTAL As Integer,
                                                              ByVal ATE_TOTAL_PREVI As Integer,
                                                              ByVal ATE_TOTAL_COPA As Integer,
                                                              ByVal ID_PROGRA As Integer,
                                                              ByVal ATE_RETIRO As String,
                                                              ByVal SECTOR As Integer,
                                                              ByVal ATE_AVIS As String,
                                                              ByVal Interno As String,
                                                              ByVal Diag As String,
                                                              ByVal Diag2 As String,
                                                              ByVal VIH As String,
                                                              ByVal dni As String,
                                                             ByVal ID_SUBP As Long) As Integer
        Return DD_Data.IRIS_WEBF_GRABA_ATENCION_PROGRA2_PRO_SECTOR_OMI(ATE_NUM,
                                                                        ID_PACIENTE,
                                                                        ID_USUARIO,
                                                                        ATE_FUR,
                                                                        ID_PROCE,
                                                                        ID_ORDEN,
                                                                        ID_TP_PACI,
                                                                        ID_DOCTOR,
                                                                        ID_PREVE,
                                                                        ID_LOCAL,
                                                                        ID_ESTADO,
                                                                        ATE_OBS,
                                                                        ATE_CAMA,
                                                                        ATE_AÑO,
                                                                        ATE_MES,
                                                                        ATE_DIA,
                                                                        ATE_TOTAL,
                                                                        ATE_TOTAL_PREVI,
                                                                        ATE_TOTAL_COPA,
                                                                        ID_PROGRA,
                                                                        ATE_RETIRO,
                                                                        SECTOR,
                                                                        ATE_AVIS,
                                                                        Interno,
                                                                         Diag, Diag2,
                                                                        VIH,
                                                                        dni,
                                                                       ID_SUBP)
    End Function
    Function IRIS_WEBF_GRABA_ATENCION_PROGRA2_PRO_SECTOR_SAYDEX(ByVal ATE_NUM As String,
                                                              ByVal ID_PACIENTE As Integer,
                                                              ByVal ID_USUARIO As Integer,
                                                              ByVal ATE_FUR As String,
                                                              ByVal ID_PROCE As Integer,
                                                              ByVal ID_ORDEN As Integer,
                                                              ByVal ID_TP_PACI As Integer,
                                                              ByVal ID_DOCTOR As Integer,
                                                              ByVal ID_PREVE As Integer,
                                                              ByVal ID_LOCAL As Integer,
                                                              ByVal ID_ESTADO As Integer,
                                                              ByVal ATE_OBS As String,
                                                              ByVal ATE_CAMA As String,
                                                              ByVal ATE_AÑO As Integer,
                                                              ByVal ATE_MES As Integer,
                                                              ByVal ATE_DIA As Integer,
                                                              ByVal ATE_TOTAL As Integer,
                                                              ByVal ATE_TOTAL_PREVI As Integer,
                                                              ByVal ATE_TOTAL_COPA As Integer,
                                                              ByVal ID_PROGRA As Integer,
                                                              ByVal ATE_RETIRO As String,
                                                              ByVal SECTOR As Integer,
                                                              ByVal ATE_AVIS As String,
                                                              ByVal Interno As String,
                                                              ByVal Diag As String,
                                                              ByVal Diag2 As String,
                                                              ByVal VIH As String,
                                                              ByVal dni As String) As Integer
        Return DD_Data.IRIS_WEBF_GRABA_ATENCION_PROGRA2_PRO_SECTOR_SAYDEX(ATE_NUM,
                                                                        ID_PACIENTE,
                                                                        ID_USUARIO,
                                                                        ATE_FUR,
                                                                        ID_PROCE,
                                                                        ID_ORDEN,
                                                                        ID_TP_PACI,
                                                                        ID_DOCTOR,
                                                                        ID_PREVE,
                                                                        ID_LOCAL,
                                                                        ID_ESTADO,
                                                                        ATE_OBS,
                                                                        ATE_CAMA,
                                                                        ATE_AÑO,
                                                                        ATE_MES,
                                                                        ATE_DIA,
                                                                        ATE_TOTAL,
                                                                        ATE_TOTAL_PREVI,
                                                                        ATE_TOTAL_COPA,
                                                                        ID_PROGRA,
                                                                        ATE_RETIRO,
                                                                        SECTOR,
                                                                        ATE_AVIS,
                                                                        Interno,
                                                                         Diag, Diag2,
                                                                        VIH,
                                                                        dni)
    End Function


    Function IRIS_WEBF_GRABA_ATENCION_PROGRA2_PRO_SECTOR_SAYDEX_POSTA(ByVal ATE_NUM As String,
                                                              ByVal ID_PACIENTE As Integer,
                                                              ByVal ID_USUARIO As Integer,
                                                              ByVal ATE_FUR As String,
                                                              ByVal ID_PROCE As Integer,
                                                              ByVal ID_ORDEN As Integer,
                                                              ByVal ID_TP_PACI As Integer,
                                                              ByVal ID_DOCTOR As Integer,
                                                              ByVal ID_PREVE As Integer,
                                                              ByVal ID_LOCAL As Integer,
                                                              ByVal ID_ESTADO As Integer,
                                                              ByVal ATE_OBS As String,
                                                              ByVal ATE_CAMA As String,
                                                              ByVal ATE_AÑO As Integer,
                                                              ByVal ATE_MES As Integer,
                                                              ByVal ATE_DIA As Integer,
                                                              ByVal ATE_TOTAL As Integer,
                                                              ByVal ATE_TOTAL_PREVI As Integer,
                                                              ByVal ATE_TOTAL_COPA As Integer,
                                                              ByVal ID_PROGRA As Integer,
                                                              ByVal ATE_RETIRO As String,
                                                              ByVal SECTOR As Integer,
                                                              ByVal ATE_AVIS As String,
                                                              ByVal Interno As String,
                                                              ByVal Diag As String,
                                                              ByVal Diag2 As String,
                                                              ByVal VIH As String,
                                                              ByVal dni As String) As Integer
        Return DD_Data.IRIS_WEBF_GRABA_ATENCION_PROGRA2_PRO_SECTOR_SAYDEX_POSTA(ATE_NUM,
                                                                        ID_PACIENTE,
                                                                        ID_USUARIO,
                                                                        ATE_FUR,
                                                                        ID_PROCE,
                                                                        ID_ORDEN,
                                                                        ID_TP_PACI,
                                                                        ID_DOCTOR,
                                                                        ID_PREVE,
                                                                        ID_LOCAL,
                                                                        ID_ESTADO,
                                                                        ATE_OBS,
                                                                        ATE_CAMA,
                                                                        ATE_AÑO,
                                                                        ATE_MES,
                                                                        ATE_DIA,
                                                                        ATE_TOTAL,
                                                                        ATE_TOTAL_PREVI,
                                                                        ATE_TOTAL_COPA,
                                                                        ID_PROGRA,
                                                                        ATE_RETIRO,
                                                                        SECTOR,
                                                                        ATE_AVIS,
                                                                        Interno,
                                                                         Diag, Diag2,
                                                                        VIH,
                                                                        dni)
    End Function
    Function IRIS_WEBF_CMVM_GRABA_ATENCION_PROGRA2_PRO_SECTOR_SIDRA(ByVal ATE_NUM As String,
                                                            ByVal ID_PACIENTE As Integer,
                                                            ByVal ID_USUARIO As Integer,
                                                            ByVal ATE_FUR As String,
                                                            ByVal ID_PROCE As Integer,
                                                            ByVal ID_ORDEN As Integer,
                                                            ByVal ID_TP_PACI As Integer,
                                                            ByVal ID_DOCTOR As Integer,
                                                            ByVal ID_PREVE As Integer,
                                                            ByVal ID_LOCAL As Integer,
                                                            ByVal ID_ESTADO As Integer,
                                                            ByVal ATE_OBS As String,
                                                            ByVal ATE_CAMA As String,
                                                            ByVal ATE_AÑO As Integer,
                                                            ByVal ATE_MES As Integer,
                                                            ByVal ATE_DIA As Integer,
                                                            ByVal ATE_TOTAL As Integer,
                                                            ByVal ATE_TOTAL_PREVI As Integer,
                                                            ByVal ATE_TOTAL_COPA As Integer,
                                                            ByVal ID_PROGRA As Integer,
                                                            ByVal ATE_RETIRO As String,
                                                            ByVal SECTOR As Integer,
                                                            ByVal ATE_AVIS As String,
                                                            ByVal Interno As String,
                                                            ByVal Diag As String,
                                                            ByVal Diag2 As String,
                                                            ByVal VIH As String,
                                                            ByVal dni As String,
                                                            ByVal ATE_TM As String) As Integer
        Return DD_Data.IRIS_WEBF_CMVM_GRABA_ATENCION_PROGRA2_PRO_SECTOR_SIDRA(ATE_NUM,
                                                                        ID_PACIENTE,
                                                                        ID_USUARIO,
                                                                        ATE_FUR,
                                                                        ID_PROCE,
                                                                        ID_ORDEN,
                                                                        ID_TP_PACI,
                                                                        ID_DOCTOR,
                                                                        ID_PREVE,
                                                                        ID_LOCAL,
                                                                        ID_ESTADO,
                                                                        ATE_OBS,
                                                                        ATE_CAMA,
                                                                        ATE_AÑO,
                                                                        ATE_MES,
                                                                        ATE_DIA,
                                                                        ATE_TOTAL,
                                                                        ATE_TOTAL_PREVI,
                                                                        ATE_TOTAL_COPA,
                                                                        ID_PROGRA,
                                                                        ATE_RETIRO,
                                                                        SECTOR,
                                                                        ATE_AVIS,
                                                                        Interno,
                                                                         Diag, Diag2,
                                                                        VIH,
                                                                        dni,
                                                                        ATE_TM)
    End Function
    Function IRIS_WEBF_CMVM_GRABA_ATENCION_PROGRA2_PRO_SECTOR_AVIS_3_NEW_CAJA(ByVal ATE_NUM As String,
                                                          ByVal ID_PACIENTE As Integer,
                                                          ByVal ID_USUARIO As Integer,
                                                          ByVal ATE_FUR As String,
                                                          ByVal ID_PROCE As Integer,
                                                          ByVal ID_ORDEN As Integer,
                                                          ByVal ID_TP_PACI As Integer,
                                                          ByVal ID_DOCTOR As Integer,
                                                          ByVal ID_PREVE As Integer,
                                                          ByVal ID_LOCAL As Integer,
                                                          ByVal ID_ESTADO As Integer,
                                                          ByVal ATE_OBS As String,
                                                          ByVal ATE_CAMA As String,
                                                          ByVal ATE_AÑO As Integer,
                                                          ByVal ATE_MES As Integer,
                                                          ByVal ATE_DIA As Integer,
                                                          ByVal ATE_TOTAL As Integer,
                                                          ByVal ATE_TOTAL_PREVI As Integer,
                                                          ByVal ATE_TOTAL_COPA As Integer,
                                                          ByVal ID_PROGRA As Integer,
                                                          ByVal ATE_RETIRO As String,
                                                          ByVal SECTOR As Integer,
                                                          ByVal ATE_AVIS As String,
                                                          ByVal Interno As String,
                                                          ByVal Diag As String,
                                                          ByVal Diag2 As String,
                                                          ByVal VIH As String,
                                                          ByVal dni As String,
                                                          ByVal ATE_TM As String,
                                                          ByVal ATE_V_SISTEMA As Integer,                '1       'PARÁMETROS  CAJA
                                                          ByVal ATE_V_BENEF As Integer,                  '2
                                                          ByVal ATE_V_CF As Integer,                     '3
                                                          ByVal ATE_V_CF_FP As Integer,                  '4
                                                          ByVal ATE_V_CP As Integer,                       '5
                                                          ByVal ATE_V_CP_FP As Integer,                  '6
                                                          ByVal ATE_V_BOLETA As Integer,                '7
                                                          ByVal ATE_V_PAGADO As Integer,                   '8
                                                           ByVal ATE_V_SEG_COMP As Integer) As Integer     '9
        Return DD_Data.IRIS_WEBF_CMVM_GRABA_ATENCION_PROGRA2_PRO_SECTOR_AVIS_3_NEW_CAJA(ATE_NUM,
                                                                        ID_PACIENTE,
                                                                        ID_USUARIO,
                                                                        ATE_FUR,
                                                                        ID_PROCE,
                                                                        ID_ORDEN,
                                                                        ID_TP_PACI,
                                                                        ID_DOCTOR,
                                                                        ID_PREVE,
                                                                        ID_LOCAL,
                                                                        ID_ESTADO,
                                                                        ATE_OBS,
                                                                        ATE_CAMA,
                                                                        ATE_AÑO,
                                                                        ATE_MES,
                                                                        ATE_DIA,
                                                                        ATE_TOTAL,
                                                                        ATE_TOTAL_PREVI,
                                                                        ATE_TOTAL_COPA,
                                                                        ID_PROGRA,
                                                                        ATE_RETIRO,
                                                                        SECTOR,
                                                                        ATE_AVIS,
                                                                        Interno,
                                                                         Diag, Diag2,
                                                                        VIH,
                                                                        dni,
                                                                        ATE_TM,
                                                                        ATE_V_SISTEMA,                '1
                                                                        ATE_V_BENEF,                  '2
                                                                        ATE_V_CF,                     '3
                                                                        ATE_V_CF_FP,                  '4
                                                                        ATE_V_CP,                     '5
                                                                        ATE_V_CP_FP,                  '6
                                                                        ATE_V_BOLETA,                 '7
                                                                        ATE_V_PAGADO,                   '8
                                                                        ATE_V_SEG_COMP)               '9
    End Function
    Function IRIS_WEBF_CMVM_GRABA_ATENCION_PROGRA2_PRO_SECTOR_AVIS_3_NEW_CAJA_MAS_SC(ByVal ATE_NUM As String,
                                                          ByVal ID_PACIENTE As Integer,
                                                          ByVal ID_USUARIO As Integer,
                                                          ByVal ATE_FUR As String,
                                                          ByVal ID_PROCE As Integer,
                                                          ByVal ID_ORDEN As Integer,
                                                          ByVal ID_TP_PACI As Integer,
                                                          ByVal ID_DOCTOR As Integer,
                                                          ByVal ID_PREVE As Integer,
                                                          ByVal ID_LOCAL As Integer,
                                                          ByVal ID_ESTADO As Integer,
                                                          ByVal ATE_OBS As String,
                                                          ByVal ATE_CAMA As String,
                                                          ByVal ATE_AÑO As Integer,
                                                          ByVal ATE_MES As Integer,
                                                          ByVal ATE_DIA As Integer,
                                                          ByVal ATE_TOTAL As Integer,
                                                          ByVal ATE_TOTAL_PREVI As Integer,
                                                          ByVal ATE_TOTAL_COPA As Integer,
                                                          ByVal ID_PROGRA As Integer,
                                                          ByVal ATE_RETIRO As String,
                                                          ByVal SECTOR As Integer,
                                                          ByVal ATE_AVIS As String,
                                                          ByVal Interno As String,
                                                          ByVal Diag As String,
                                                          ByVal Diag2 As String,
                                                          ByVal VIH As String,
                                                          ByVal dni As String,
                                                          ByVal ATE_TM As String,
                                                          ByVal ATE_V_SISTEMA As Integer,                '1       'PARÁMETROS  CAJA
                                                          ByVal ATE_V_BENEF As Integer,                  '2
                                                          ByVal ATE_V_CF As Integer,                     '3
                                                          ByVal ATE_V_CF_FP As Integer,                  '4
                                                          ByVal ATE_V_CP As Integer,                       '5
                                                          ByVal ATE_V_CP_FP As Integer,                  '6
                                                          ByVal ATE_V_BOLETA As Integer,                '7
                                                          ByVal ATE_V_PAGADO As Integer,                   '8
                                                           ByVal ATE_V_SEG_COMP As Integer,
                                                                                     ByVal ATE_V_SC_2 As Integer) As Integer     '9
        Return DD_Data.IRIS_WEBF_CMVM_GRABA_ATENCION_PROGRA2_PRO_SECTOR_AVIS_3_NEW_CAJA_MAS_SC(ATE_NUM,
                                                                        ID_PACIENTE,
                                                                        ID_USUARIO,
                                                                        ATE_FUR,
                                                                        ID_PROCE,
                                                                        ID_ORDEN,
                                                                        ID_TP_PACI,
                                                                        ID_DOCTOR,
                                                                        ID_PREVE,
                                                                        ID_LOCAL,
                                                                        ID_ESTADO,
                                                                        ATE_OBS,
                                                                        ATE_CAMA,
                                                                        ATE_AÑO,
                                                                        ATE_MES,
                                                                        ATE_DIA,
                                                                        ATE_TOTAL,
                                                                        ATE_TOTAL_PREVI,
                                                                        ATE_TOTAL_COPA,
                                                                        ID_PROGRA,
                                                                        ATE_RETIRO,
                                                                        SECTOR,
                                                                        ATE_AVIS,
                                                                        Interno,
                                                                         Diag, Diag2,
                                                                        VIH,
                                                                        dni,
                                                                        ATE_TM,
                                                                        ATE_V_SISTEMA,                '1
                                                                        ATE_V_BENEF,                  '2
                                                                        ATE_V_CF,                     '3
                                                                        ATE_V_CF_FP,                  '4
                                                                        ATE_V_CP,                     '5
                                                                        ATE_V_CP_FP,                  '6
                                                                        ATE_V_BOLETA,                 '7
                                                                        ATE_V_PAGADO,                 '8
                                                                        ATE_V_SEG_COMP,               '9
                                                                            ATE_V_SC_2)
    End Function

    Function IRIS_WEBF_CMVM_GRABA_REL_COPAGO(ByVal ID_ATENCION As Integer,
                                            ByVal ID_USUARIO As Integer,
                                            ByVal ATE_FECHA As Date,
                                            ByVal ATE_TP_COPAGO_1 As String,
                                             ByVal ATE_VALOR_COPAGO_1 As String,
                                             ByVal ATE_TP_COPAGO_2 As String,
                                             ByVal ATE_VALOR_COPAGO_2 As String,
                                             ByVal ATE_V_CP_FP_2 As Integer,
                                             ByVal ATE_V_CP_2 As String,
                                             ByVal ATE_TP_PARTICULAR_1 As String,
                                             ByVal ATE_VALOR_PARTICULAR_1 As String,
                                             ByVal ATE_TP_PARTICULAR_2 As String,
                                             ByVal ATE_VALOR_PARTICULAR_2 As String) As Integer
        Return DD_Data.IRIS_WEBF_CMVM_GRABA_REL_COPAGO(ID_ATENCION,
                                                       ID_USUARIO,
                                                       ATE_FECHA,
                                                       ATE_TP_COPAGO_1,
                                                       ATE_VALOR_COPAGO_1,
                                                       ATE_TP_COPAGO_2,
                                                       ATE_VALOR_COPAGO_2,
                                                       ATE_V_CP_FP_2,
                                                       ATE_V_CP_2,
                                                       ATE_TP_PARTICULAR_1,
                                                       ATE_VALOR_PARTICULAR_1,
                                                       ATE_TP_PARTICULAR_2,
                                                       ATE_VALOR_PARTICULAR_2)
    End Function

    Function IRIS_WEBF_CMVM_GRABA_ATENCION_PROGRA2_PRO_SECTOR_AVIS_3_NEW_CAJA_MAS_SC_CHANGE_TP_PAGO(ByVal ID_ATENCION As Integer,
                                                                                                    ByVal VALOR_PREVI As Integer,
                                                                                                    ByVal VALOR_BENEFI As Integer,
                                                                                                    ByVal VALOR_SC As Integer,
                                                                                                    ByVal VALOR_PAGADO As Integer,
                                                                                                    ByVal VALOR_CF As Integer,
                                                                                                    ByVal VALOR_CP As Integer) As Integer
        Return DD_Data.IRIS_WEBF_CMVM_GRABA_ATENCION_PROGRA2_PRO_SECTOR_AVIS_3_NEW_CAJA_MAS_SC_CHANGE_TP_PAGO(ID_ATENCION,
                                                                                                              VALOR_PREVI,
                                                                                                              VALOR_BENEFI,
                                                                                                              VALOR_SC,
                                                                                                              VALOR_PAGADO,
                                                                                                              VALOR_CF,
                                                                                                              VALOR_CP)
    End Function
    Function IRIS_WEBF_CMVM_GRABA_LOG_IMED_VTABONINTERFAZ(ByVal ID_USUARIO As Integer,
                                                          ByVal ID_PROCEDENCIA As Integer,
                                                          ByVal ID_PREVISION As Integer,
                                                          ByVal RUT_PAC_LOG As String,
                                                          ByVal MENSAJE_LOG As String) As Integer
        Return DD_Data.IRIS_WEBF_CMVM_GRABA_LOG_IMED_VTABONINTERFAZ(ID_USUARIO, ID_PROCEDENCIA, ID_PREVISION, RUT_PAC_LOG, MENSAJE_LOG)
    End Function
    Function IRIS_WEBF_CMVM_GRABA_ATENCION_PROGRA2_PRO_SECTOR_AVIS_3_NEW_CAJA_MAS_SC_MAS_BONOS_IMED(ByVal ATE_NUM As String,
                                                        ByVal ID_PACIENTE As Integer,
                                                        ByVal ID_USUARIO As Integer,
                                                        ByVal ATE_FUR As String,
                                                        ByVal ID_PROCE As Integer,
                                                        ByVal ID_ORDEN As Integer,
                                                        ByVal ID_TP_PACI As Integer,
                                                        ByVal ID_DOCTOR As Integer,
                                                        ByVal ID_PREVE As Integer,
                                                        ByVal ID_LOCAL As Integer,
                                                        ByVal ID_ESTADO As Integer,
                                                        ByVal ATE_OBS As String,
                                                        ByVal ATE_CAMA As String,
                                                        ByVal ATE_AÑO As Integer,
                                                        ByVal ATE_MES As Integer,
                                                        ByVal ATE_DIA As Integer,
                                                        ByVal ATE_TOTAL As Integer,
                                                        ByVal ATE_TOTAL_PREVI As Integer,
                                                        ByVal ATE_TOTAL_COPA As Integer,
                                                        ByVal ID_PROGRA As Integer,
                                                        ByVal ATE_RETIRO As String,
                                                        ByVal SECTOR As Integer,
                                                        ByVal ATE_AVIS As String,
                                                        ByVal Interno As String,
                                                        ByVal Diag As String,
                                                        ByVal Diag2 As String,
                                                        ByVal VIH As String,
                                                        ByVal dni As String,
                                                        ByVal ATE_TM As String,
                                                        ByVal ATE_V_SISTEMA As Integer,                '1       'PARÁMETROS  CAJA
                                                        ByVal ATE_V_BENEF As Integer,                  '2
                                                        ByVal ATE_V_CF As Integer,                     '3
                                                        ByVal ATE_V_CF_FP As Integer,                  '4
                                                        ByVal ATE_V_CP As Integer,                       '5
                                                        ByVal ATE_V_CP_FP As Integer,                  '6
                                                        ByVal ATE_V_BOLETA As Integer,                '7
                                                        ByVal ATE_V_PAGADO As Integer,                   '8
                                                        ByVal ATE_V_SEG_COMP As Integer,
                                                        ByVal ATE_V_SC_2 As Integer,
                                                        ByVal GLOBAL_BONO_NUM As String) As Integer
        Return DD_Data.IRIS_WEBF_CMVM_GRABA_ATENCION_PROGRA2_PRO_SECTOR_AVIS_3_NEW_CAJA_MAS_SC_MAS_BONOS_IMED(ATE_NUM,
                                                                        ID_PACIENTE,
                                                                        ID_USUARIO,
                                                                        ATE_FUR,
                                                                        ID_PROCE,
                                                                        ID_ORDEN,
                                                                        ID_TP_PACI,
                                                                        ID_DOCTOR,
                                                                        ID_PREVE,
                                                                        ID_LOCAL,
                                                                        ID_ESTADO,
                                                                        ATE_OBS,
                                                                        ATE_CAMA,
                                                                        ATE_AÑO,
                                                                        ATE_MES,
                                                                        ATE_DIA,
                                                                        ATE_TOTAL,
                                                                        ATE_TOTAL_PREVI,
                                                                        ATE_TOTAL_COPA,
                                                                        ID_PROGRA,
                                                                        ATE_RETIRO,
                                                                        SECTOR,
                                                                        ATE_AVIS,
                                                                        Interno,
                                                                         Diag, Diag2,
                                                                        VIH,
                                                                        dni,
                                                                        ATE_TM,
                                                                        ATE_V_SISTEMA,                '1
                                                                        ATE_V_BENEF,                  '2
                                                                        ATE_V_CF,                     '3
                                                                        ATE_V_CF_FP,                  '4
                                                                        ATE_V_CP,                     '5
                                                                        ATE_V_CP_FP,                  '6
                                                                        ATE_V_BOLETA,                 '7
                                                                        ATE_V_PAGADO,                 '8
                                                                        ATE_V_SEG_COMP,               '9
                                                                        ATE_V_SC_2,
                                                                        GLOBAL_BONO_NUM)
    End Function
    Function IRIS_WEBF_CMVM_ESTADO_BONO_IMED(ByVal ID_USUARIO As Integer,
                                            ByVal COMENTARIO As String,
                                             ByVal FOLIO_BONO As String) As Integer
        Return DD_Data.IRIS_WEBF_CMVM_ESTADO_BONO_IMED(ID_USUARIO, COMENTARIO, FOLIO_BONO)
    End Function
    Function IRIS_WEBF_CMVM_ANULA_ESTADO_BONO_IMED(ByVal ID_USUARIO As Integer,
                                        ByVal COMENTARIO As String,
                                                   ByVal folio_bono As String) As Integer
        Return DD_Data.IRIS_WEBF_CMVM_ANULA_ESTADO_BONO_IMED(ID_USUARIO, COMENTARIO, folio_bono)
    End Function
End Class